### ISSUE TITLE
Running unity's example scene make application not responding

### ISSUE THREAD

**Issue by modanub** [fuziki/mcDesktopCapture#17]
Everytime I tried to run both example scene 1 and 2 will make my unity editor not responding. I have slept for 10 hours and come back to see that it still not responding. I tried to change the version of my editor, and it still didn't solve my issue.

**To Reproduce**
1. Download & open the example project.
2. Open SampleScene1 or SampleScene2.
3. Run the play mode.

- Operating System: 13.2 (22D49)
- Unity Version: 2021.3.20f1 and 2023.1.0a26
- Device: MacBook Pro 14-inch, 2021 (M1 Pro)

**Comment by fuziki** [comment]
Thanks for your report.

Did you add Unity.app to Preferences?
Refer to the Installation chapter of the README.

**Comment by modanub** [comment]
I did follow the README installation guide.
<img width="488" alt="image" src="https://user-images.githubusercontent.com/82494178/224602430-830f1a88-9743-457b-be5a-8b04a800d87c.png">

**Comment by modanub** [comment]
The issue seem to be resolve after a system restart after allowing Unity Editor and Unity Hub to capture screen inside system preferences. (Also when selecting Unity Editor's path to allow screen recording, select the version that going to use the lib).  Sorry for wasting your time @fuziki .
