### ISSUE TITLE
Crash when calling mcDesktopCapture_clearFrame

### ISSUE THREAD

**Issue by DenchiSoft** [fuziki/mcDesktopCapture#9]
I've just tried the new version of the plugin and it's working very well with multiple displays. Thank you for the great work!!

The only thing I've noticed is that it sometimes crashes when calling `mcDesktopCapture_clearFrame(IntPtr texturePtr)`.

You can reproduce it like this:

- Call `StartCapture(0)`, then run `GetCurrentFrame()` repeatedly.
- Call `StopCapture()`
- Call `StartCapture(0)` again.
- Call `GetCurrentFrame()`

That's when the crash happens, maybe because the pointer in `mcDesktopCapture_clearFrame(texturePtr)` is invalid after stopping the capture and restarting it.

If I set `inited` to false in `StopCapture()`, it doesn't happen. It's not a big deal but if it's something you can fix on your side, it would be cool!

I've attached the crash log here: [crash.txt](https://github.com/fuziki/mcDesktopCapture/files/7229618/crash.txt)

**Comment by fuziki** [comment]
Thank you for your report.

There is no safe way to run `mcDesktopCapture_clearFrame`.
Because I don't know how to safely cast it to the c++ layer that bridges c# and swift.

I plan to provide more abstract API, since `mcDesktopCapture_clearFrame` is very difficult.

**Comment by fuziki** [comment]
Updated library, `mcDesktopCapture_clearFrame` is now deprecated.
